services:
  server:
    image: part4_server:v3
    container_name: 
      server
    tty: true

  nginx-proxy:
    image: nginx:latest
    container_name: 
      nginx                 
    depends_on:
      - server                                
    ports:
      - "80:8080"                                     
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
    tty: true   